version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./data/dev.db
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_SECRET=${BINANCE_SECRET}
      - BINANCE_SANDBOX=true
    volumes:
      - ./data:/app/data
    restart: unless-stopped

  # Uncomment for PostgreSQL in production
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: crypto_bot
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
